/**
* @Author            : jh.jung
* @Description 		 : 동적 Trigger Handler 실행을 위한 Interface Class
* @Target            : 만트럭 TriggerHandler 참조
* @Modification Log
  Ver      Date            Author           Modification
  ===================================================================================
  1.0      2026-01-29      jh.jung           Created
*/
public interface ITrigger {
    // Run Trigger Handler method
    void run();
}